version: 2

registries:
  my-npm-pkg:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.PAT}}

updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries: 
      - my-npm-pkg
    schedule:
      interval: "daily"
    open-pull-requests-limit: 15
    
