name: AutoRelease

on: [workflow_dispatch]
#  push: 
#    tags:
#      - 'v*'

jobs:
  build:
    # if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
          
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
          
      - name: Determine Version
        id:   gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        
      - name: 'Change NPM version'
        uses: reedyuk/npm-version@1.1.1
        with:
          version: $GITVERSION_SEMVER
          
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci
      - run: npm test
      
      - name: Create release with GitReleaseManager
        uses: gittools/actions/gitreleasemanager/publish@v0.9.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: 'wulfland'
          repository: 'package-demo'
          milestone: $GITVERSION_SEMVER
          name: $GITVERSION_SEMVER
          assets:  '*'

